# path to root directory
root_dir: ./

# path to resources directory
resource_dir: ${paths.root_dir}/resources/
input_dir: ${paths.resource_dir}/inputs/
output_dir: ${paths.resource_dir}/outputs/${hydra:job.override_dirname}/
artifact_dir: ${paths.output_dir}/artifacts/
misc_dir: ${paths.resource_dir}/misc/

submission_dir: ${paths.artifact_dir} # inference output
